# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cd3a0f2e01b93a962f9abbca08a27dbd2e857e6c59823a235962f322787d9a26d69b5d07a2a3c0f937eee68ef02ad9a4f12e320887c921c38dfc4f21a6f2cc0

test:
  secret_key_base: 59dcc1930495a7d5132f2b47afa35633805883824d4083d0d0a92c3e492b8096ce97369b4e5ed8d3aa40d8affb8e571718774cc999d398bec7a6a80ee227d568

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
